### ISSUE TITLE
Samsung SGS 3 - failure to open a deeplink

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#393]
Failure when handling a deeplink 

I open my mal box with a browser. I tap the deeplink of the invitation email. I'm asked to handle the deeplink with a browser or the MDM agent. I choose the MDM agent. It crashes

adb logcat 
```J
D/audio_hw_primary( 1898): select_output_device: AUDIO_DEVICE_OUT_SPEAKER
I/PackageManager( 2327):   Action: "android.intent.action.VIEW"
I/PackageManager( 2327):   Category: "android.intent.category.BROWSABLE"
I/PackageManager( 2327):   Category: "android.intent.category.DEFAULT"
I/PackageManager( 2327):   Scheme: "http"
I/PackageManager( 2327):   Authority: "flyve.org": -1
I/PackageManager( 2327):   Path: "PatternMatcher{PREFIX: /deeplink}"
I/PackageManager( 2327): Adding preferred activity ComponentInfo{org.flyve.mdm.agent/org.flyve.mdm.agent.ui.StartEnrollmentActivity} for user 0 :
I/Timeline(12017): Timeline: Activity_launch_request id:org.flyve.mdm.agent time:44239553
I/ActivityManager( 2327): START u0 {act=android.intent.action.VIEW cat=[android.intent.category.BROWSABLE] dat=http://flyve.org/deeplink/?data=aHR0cHM6Ly9kZXYuZmx5dmUub3JnL2dscGkvYXBpcmVzdC5waHBcO2w1dDRpcGN1cHN2djExdHMwNThqbDFkbDVmZ2dhbnI2MzY5Y2VxaHFcOzk1MGI0ZjU1MGMwMDU3NjE0ODg0ODFkZDVlODg1OTMyNjZkYTRlY2U0ZDU2YTFjNWNlMWI1Y2VhYmNjMzkyOTdcO0dyZWF0IHN1cHBvcnRcOyszMyAxMjM0NTY3ODlcO2h0dHBzOi8vbXlncmVhdHN1cHBvcnQuY29tXDtncmVhdHN1cHBvcnRAZXhhbXBsZS5jb20= flg=0x3000000 cmp=org.flyve.mdm.agent/.ui.StartEnrollmentActivity (has extras)} from pid 12017
D/AndroidRuntime(12039): Shutting down VM
W/dalvikvm(12039): threadid=1: thread exiting with uncaught exception (group=0x418dcce0)
W/Bugsnag (12039): Could not check if app is in the foreground, we recommend granting the 'android.permission.GET_TASKS' permission
W/Bugsnag (12039): Could not get active screen information, we recommend granting the 'android.permission.GET_TASKS' permission
W/ActivityManager( 2327): Permission Denial: getTasks() from pid=12039, uid=10080 requires android.permission.GET_TASKS
W/ActivityManager( 2327): Permission Denial: getTasks() from pid=12039, uid=10080 requires android.permission.GET_TASKS
I/Bugsnag (12039): Saved unsent error to disk (/data/data/org.flyve.mdm.agent/cache/bugsnag-errors/1524873776751.json) 
I/Bugsnag (12039): Sending 1 saved error(s) to Bugsnag
E/AndroidRuntime(12039): FATAL EXCEPTION: main
E/AndroidRuntime(12039): Process: org.flyve.mdm.agent, PID: 12039
E/AndroidRuntime(12039): java.lang.RuntimeException: Unable to start activity ComponentInfo{org.flyve.mdm.agent/org.flyve.mdm.agent.ui.StartEnrollmentActivity}: java.lang.NullPointerException: uriString
E/AndroidRuntime(12039): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2212)
E/AndroidRuntime(12039): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2271)
E/AndroidRuntime(12039): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
E/AndroidRuntime(12039): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1205)
E/AndroidRuntime(12039): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(12039): 	at android.os.Looper.loop(Looper.java:136)
E/AndroidRuntime(12039): 	at android.app.ActivityThread.main(ActivityThread.java:5146)
E/AndroidRuntime(12039): 	at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(12039): 	at java.lang.reflect.Method.invoke(Method.java:515)
E/AndroidRuntime(12039): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:732)
E/AndroidRuntime(12039): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:566)
E/AndroidRuntime(12039): 	at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(12039): Caused by: java.lang.NullPointerException: uriString
E/AndroidRuntime(12039): 	at android.net.Uri$StringUri.<init>(Uri.java:467)
E/AndroidRuntime(12039): 	at android.net.Uri$StringUri.<init>(Uri.java:457)
E/AndroidRuntime(12039): 	at android.net.Uri.parse(Uri.java:429)
E/AndroidRuntime(12039): 	at org.flyve.mdm.agent.ui.StartEnrollmentActivity.onCreate(StartEnrollmentActivity.java:91)
E/AndroidRuntime(12039): 	at android.app.Activity.performCreate(Activity.java:5231)
E/AndroidRuntime(12039): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
E/AndroidRuntime(12039): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2169)
E/AndroidRuntime(12039): 	... 11 more
W/ActivityManager( 2327):   Force finishing activity org.flyve.mdm.agent/.ui.StartEnrollmentActivity
W/Bugsnag (12039): Problem sending unsent error from disk
W/Bugsnag (12039): com.bugsnag.android.ErrorReportApiClient$BadResponseException: Got non-200 response code (302) from http://demo.flyve.org
W/Bugsnag (12039): 	at com.bugsnag.android.DefaultHttpClient.postReport(DefaultHttpClient.java:49)
W/Bugsnag (12039): 	at com.bugsnag.android.ErrorStore.flushErrorReport(ErrorStore.java:126)
W/Bugsnag (12039): 	at com.bugsnag.android.ErrorStore.access$000(ErrorStore.java:23)
W/Bugsnag (12039): 	at com.bugsnag.android.ErrorStore$2.run(ErrorStore.java:113)
W/Bugsnag (12039): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/Bugsnag (12039): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/Bugsnag (12039): 	at java.lang.Thread.run(Thread.java:841)
W/ActivityManager( 2327): Activity pause timeout for ActivityRecord{41db4278 u0 org.flyve.mdm.agent/.ui.StartEnrollmentActivity t24 f}
D/WebViewTimersControl(11457): onBrowserActivityResume
D/WebViewTimersControl(11457): Resuming webview timers, view=com.android.browser.BrowserWebView{41e5e388 VFEDHVCL .F...... 0,0-720,1230}
I/Timeline(11457): Timeline: Activity_idle id: android.os.BinderProxy@41d992e0 time:44240885
I/Timeline( 2327): Timeline: Activity_windows_visible id: ActivityRecord{41ed6960 u0 com.android.browser/.BrowserActivity t19} time:44241628
```

**Comment by btry** [comment]
The issue seems to be  there

https://github.com/flyve-mdm/android-mdm-agent/blob/develop/app/src/main/java/org/flyve/mdm/agent/ui/StartEnrollmentActivity.java#L91

- The code enters line 91 even if I try to enroll with a deeplink
- bundle.getString gets a string with the key **data** but the deeplink is stored in t he key **dat** (typo ?)

**Comment by btry** [comment]
Debug session

![image](https://user-images.githubusercontent.com/14139801/39393106-5c2f4eb2-4ac1-11e8-9f9b-6e8721d3a3a0.png)
