### ISSUE TITLE
Agent crash on disable status bar

### ISSUE THREAD

**Issue by DIOHz0r** [flyve-mdm/android-mdm-agent#412]
**Describe the bug**

**To Reproduce**
1. Go to web/backend policies
2. Set "disable status bar" to on
3. Apply policy
4. Go to mobile and open the agent app

**Expected behavior**
No crash on app

**Smartphone (please complete the following information):**
 - Device: Lenovo a2010
 - OS: android

**Additional context**
```J
05-03 17:53:32.176 609-609/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.flyve.mdm.agent, PID: 609
    java.lang.NoSuchMethodError: No virtual method setStatusBarDisabled(Landroid/content/ComponentName;Z)Z in class Landroid/app/admin/DevicePolicyManager; or its super classes (declaration of 'android.app.admin.DevicePolicyManager' appears in /system/framework/framework.jar)
        at org.flyve.mdm.agent.services.PoliciesDeviceManager.disableStatusBar(PoliciesDeviceManager.java:95)
        at org.flyve.mdm.agent.services.PoliciesController.disableStatusBar(PoliciesController.java:505)
        at org.flyve.mdm.agent.services.MQTTService.messageArrived(MQTTService.java:1015)
        at org.eclipse.paho.android.service.MqttAndroidClient.messageArrivedAction(MqttAndroidClient.java:1446)
        at org.eclipse.paho.android.service.MqttAndroidClient.onReceive(MqttAndroidClient.java:1268)
        at android.support.v4.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:311)
        at android.support.v4.content.LocalBroadcastManager.access$000(LocalBroadcastManager.java:47)
        at android.support.v4.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:120)
        at android.os.Handler.dispatchMessage(Handler.java:111)
        at android.os.Looper.loop(Looper.java:194)
        at android.app.ActivityThread.main(ActivityThread.java:5624)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
```

**Comment by rafaelje** [comment]
the setStatusBarDisabled is implemented in API level 23 (Marshmallow 6.0) and require root/system permission, need to validate the API number to check if is available
