### ISSUE TITLE
Creating unit test with Mockito, Roboelectric and powermock 

### ISSUE THREAD

**Issue by rafaelje** [flyve-mdm/android-mdm-agent#499]
To improve the mandatory test present on the core like deeplink, enrollment, permission, user, and walkthrough.

The agent has a complete MVP pattern and these tests were created with the instrumented test wish make slow, in this PR I'm moving the model and presenter from instrumented test to unit test with a more clear idea for contributors.

With support for these tools:

- Powermock
To mock static class

- Robolectric
To create a real Android Context with out instrumented test

- Mockito
To create basic mocks

**Comment by rafaelje** [comment]
Creating the test for getActiveSessionToken() got a problem when try to mix Robolectric with PowerMock after solve many problems got this at last:

```
	at android.support.multidex.MultiDex.install(MultiDex.java:121)
	at org.flyve.mdm.agent.ui.MDMAgent.attachBaseContext(MDMAgent.java:50)
	at android.app.Application.attach(Application.java:181)
	at org.robolectric.util.ReflectionHelpers.callInstanceMethod(ReflectionHelpers.java:249)
	at org.robolectric.shadows.ShadowApplication.callAttach(ShadowApplication.java:136)
	at org.robolectric.android.internal.ParallelUniverse.setUpApplicationState(ParallelUniverse.java:189)
	at org.robolectric.RobolectricTestRunner.beforeTest(RobolectricTestRunner.java:335)
	at org.robolectric.internal.SandboxTestRunner$2.evaluate(SandboxTestRunner.java:245)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:130)
	at org.robolectric.internal.SandboxTestRunner.runChild(SandboxTestRunner.java:42)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:84)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)
```

**Comment by rafaelje** [comment]
apparently the problem is for the incompatibility on Powermock and mockito I make some combinations and is not working yet
