### ISSUE TITLE
crash of the agent (after an apk deployment policy ?)

### ISSUE THREAD

**Issue by btry** [flyve-mdm/android-mdm-agent#577]
**Describe the bug**
The agent may crash in some unknown circumstance. Maybe when it tries to process an apk deployment policy, not sure.

```
D/Tun2Socks( 3104): INFO(tun2socks): UDP: from device 40 bytes
I/Bugsnag (27844): Sending 2 saved error(s) to Bugsnag
E/AndroidRuntime(27844): FATAL EXCEPTION: AsyncTask #5
E/AndroidRuntime(27844): Process: org.flyve.mdm.agent, PID: 27844
E/AndroidRuntime(27844): java.lang.RuntimeException: An error occured while executing doInBackground()
E/AndroidRuntime(27844): 	at android.os.AsyncTask$3.done(AsyncTask.java:304)
E/AndroidRuntime(27844): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
E/AndroidRuntime(27844): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
E/AndroidRuntime(27844): 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
E/AndroidRuntime(27844): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
E/AndroidRuntime(27844): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(27844): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(27844): 	at java.lang.Thread.run(Thread.java:818)
E/AndroidRuntime(27844): Caused by: java.lang.NullPointerException: Attempt to read from field 'android.content.pm.ApplicationInfo android.content.pm.PackageInfo.applicationInfo' on a null object reference
E/AndroidRuntime(27844): 	at org.flyve.mdm.agent.utils.Helpers.installApk(Helpers.java:105)
E/AndroidRuntime(27844): 	at org.flyve.mdm.agent.services.PoliciesFiles.downloadApk(PoliciesFiles.java:155)
E/AndroidRuntime(27844): 	at org.flyve.mdm.agent.services.PoliciesFiles.doInBackground(PoliciesFiles.java:84)
E/AndroidRuntime(27844): 	at org.flyve.mdm.agent.services.PoliciesFiles.doInBackground(PoliciesFiles.java:44)
E/AndroidRuntime(27844): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
E/AndroidRuntime(27844): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/AndroidRuntime(27844): 	... 4 more
```

**To Reproduce**
It seems the bug can reproduce when you deploy an apk from the backend and after the agent receives the policy.

**Expected behavior**

**Screenshots**
a notification on screen about a crash

**Smartphone (please complete the following information):**
 - Device: Sony Z2
 - OS: cyanogen mod android 4.1

**Additional context**

**Comment by btry** [comment]
I also noticed those errors, If they're not related to this issue, we may move them in an other ticket

```
I/org.flyve.mdm.agent(27844): ┌────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/org.flyve.mdm.agent(27844): │ Thread: AsyncTask #5
I/org.flyve.mdm.agent(27844): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/org.flyve.mdm.agent(27844): │ PoliciesFiles.getFile  (PoliciesFiles.java:208)
I/org.flyve.mdm.agent(27844): │    FlyveLog.i  (FlyveLog.java:94)
I/org.flyve.mdm.agent(27844): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/org.flyve.mdm.agent(27844): │ File exists: /storage/emulated/0/Download/at.bitfire.davdroid_245.apk
I/org.flyve.mdm.agent(27844): └────────────────────────────────────────────────────────────────────────────────────────────────────────────────
D/        (27844): Zip: EOCD not found, /storage/emulated/0/Download/at.bitfire.davdroid_245.apk is not zip
W/zipro   (27844): Error opening archive /storage/emulated/0/Download/at.bitfire.davdroid_245.apk: Invalid file
D/asset   (27844): failed to open Zip archive '/storage/emulated/0/Download/at.bitfire.davdroid_245.apk'

```

**Comment by rafaelje** [comment]
To work with this problem we are going to implement a multi thread manager

**Comment by btry** [comment]
It seems the PR above solve the issue. No more crash so far
