### ISSUE TITLE
Wipe aborts with stacktrace on lineageos 14.1 device

### ISSUE THREAD

**Issue by abma** [flyve-mdm/android-mdm-agent#617]
**Describe the bug**
when i try a remote wipe, the command is received at the phone but aborted due an error.

**To Reproduce**
send remote wipe

**Smartphone (please complete the following information):**
 - Lineageos 14.1 on ZOOED

output of logcat + stacktrace

```
10-30 18:17:52.096  8197  8197 D org.flyve.mdm.agent: ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────                                                ───────
10-30 18:17:52.097  8197  8197 D org.flyve.mdm.agent: │ Thread: main
10-30 18:17:52.097  8197  8197 D org.flyve.mdm.agent: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄                                                ┄┄┄┄┄┄┄
10-30 18:17:52.097  8197  8197 D org.flyve.mdm.agent: │ MqttModel.messageArrived  (MqttModel.java:335)
10-30 18:17:52.097  8197  8197 D org.flyve.mdm.agent: │    FlyveLog.d  (FlyveLog.java:60)
10-30 18:17:52.097  8197  8197 D org.flyve.mdm.agent: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄                                                ┄┄┄┄┄┄┄
10-30 18:17:52.097  8197  8197 D org.flyve.mdm.agent: │ - Topic: 0/agent/1c1e5571/Command/Wipe
10-30 18:17:52.097  8197  8197 D org.flyve.mdm.agent: │
10-30 18:17:52.097  8197  8197 D org.flyve.mdm.agent: │ - Message: {"wipe":"now"}
10-30 18:17:52.097  8197  8197 D org.flyve.mdm.agent: └─────────────────────────────────────────────────────────────────────────────────────────────────────────                                                ───────
10-30 18:17:52.097  8197  8197 D org.flyve.mdm.agent: ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────                                                ───────
10-30 18:17:52.098  8197  8197 D org.flyve.mdm.agent: │ Thread: main
10-30 18:17:52.098  8197  8197 D org.flyve.mdm.agent: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄                                                ┄┄┄┄┄┄┄
10-30 18:17:52.098  8197  8197 D org.flyve.mdm.agent: │ MqttModel.messageArrived  (MqttModel.java:337)
10-30 18:17:52.098  8197  8197 D org.flyve.mdm.agent: │    FlyveLog.d  (FlyveLog.java:60)
10-30 18:17:52.098  8197  8197 D org.flyve.mdm.agent: ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄                                                ┄┄┄┄┄┄┄
10-30 18:17:52.098  8197  8197 D org.flyve.mdm.agent: │ - Topic: 0/agent/1c1e5571/Command/Wipe
10-30 18:17:52.098  8197  8197 D org.flyve.mdm.agent: │
10-30 18:17:52.098  8197  8197 D org.flyve.mdm.agent: │ - Message: {"wipe":"now"}
10-30 18:17:52.098  8197  8197 D org.flyve.mdm.agent: └─────────────────────────────────────────────────────────────────────────────────────────────────────────                                                ───────
10-30 18:17:53.114  8494  8494 I uncrypt :   received command: [--wipe_data
10-30 18:17:53.114  8494  8494 I uncrypt : --reason=DevicePolicyManager.wipeData() from org.flyve.mdm.agent/.receivers.FlyveAdminReceiver
10-30 18:17:53.114  8494  8494 I uncrypt : --locale=de_DE
10-30 18:17:53.114  8494  8494 I uncrypt : ] (122)
10-30 18:17:53.115  8494  8494 E uncrypt : failed to set bootloader message: failed to find /misc partition
10-30 18:17:53.124   795  2025 E RecoverySystemService: uncrypt failed with status: -1
10-30 18:17:53.125   795  2025 W DevicePolicyManagerService: Failed requesting data wipe
10-30 18:17:53.125   795  2025 W DevicePolicyManagerService: java.io.IOException: Reboot failed (no permissions?)
10-30 18:17:53.125   795  2025 W DevicePolicyManagerService:    at android.os.RecoverySystem.bootCommand(RecoverySystem.java:718)
10-30 18:17:53.125   795  2025 W DevicePolicyManagerService:    at android.os.RecoverySystem.rebootWipeUserData(RecoverySystem.java:650)
10-30 18:17:53.125   795  2025 W DevicePolicyManagerService:    at android.os.RecoverySystem.rebootWipeUserData(RecoverySystem.java:587)
10-30 18:17:53.125   795  2025 W DevicePolicyManagerService:    at com.android.server.devicepolicy.DevicePolicyManagerService.wipeDataNoLock(DevicePolicyManager                                                Service.java:4770)
10-30 18:17:53.125   795  2025 W DevicePolicyManagerService:    at com.android.server.devicepolicy.DevicePolicyManagerService.wipeDeviceNoLock(DevicePolicyManag                                                erService.java:4818)
10-30 18:17:53.125   795  2025 W DevicePolicyManagerService:    at com.android.server.devicepolicy.DevicePolicyManagerService.wipeData(DevicePolicyManagerServic                                                e.java:4810)
10-30 18:17:53.125   795  2025 W DevicePolicyManagerService:    at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:631)
10-30 18:17:53.125   795  2025 W DevicePolicyManagerService:    at android.os.Binder.execTransact(Binder.java:565)
10-30 18:17:53.126  8494  8494 I uncrypt :   received 0, exiting now




```

**Comment by abma** [comment]
i've tried the same with an other device which worked. so possible a bug / incompatibility / problem  with the device?

not sure if this can and should be fixed by the mdm agent.

**Comment by rafaelje** [comment]
looks like a problem with the SD Card if do you have an SD Card could you remove it please and try again on your device with the problem

**Comment by iGitEktaPatel** [comment]
I am facing same problem. I am using emulator with Android Q.
There is no SDCard in emulator - selected "No SDCard" from hardware profile.
