### ISSUE TITLE
App Crash after Share the Inventory Screen

### ISSUE THREAD

**Issue by rrqq** [flyve-mdm/android-mdm-agent#762]
**Describe the bug**

App crashes after share the inventory screen -> Selecting the format -> Ok -> Process Crashed (option to restart the App)

Other details noticed in the app - The first screen doesn't show full URL on Enroll device screen.

**To Reproduce**

1. Building from develop. Deploying it to emulator Pixel 3a API 27
2. Continue standard enrollment process via QR code.
3. Give required Permissions
4. Tap ok after Inventory sharing screen format selection -> Error

**Expected behavior**
To work as desired and then enroll

**Screenshots**

![screenshot2](https://user-images.githubusercontent.com/22286811/68406382-b6415300-014f-11ea-8592-5c91cf666ad2.png)

![screenshot4](https://user-images.githubusercontent.com/22286811/68406605-1c2dda80-0150-11ea-8efe-97607ea1a272.png)

![screenshot11](https://user-images.githubusercontent.com/22286811/68406390-bc373400-014f-11ea-84a3-898bfac79ca5.png)

**Desktop (please complete the following information):**
 - Mac, Android Studio

**Smartphone (please complete the following information):**
 - Device: Pixel 3a API 27
 - OS: Android 8.1
 - Browser Chrome

**Additional context**
```
2019-11-07 11:16:27.195 1449-1525/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2019-11-07 11:16:54.212 1680-1699/system_process E/memtrack: Couldn't load memtrack module
2019-11-07 11:17:54.217 1680-1699/system_process E/memtrack: Couldn't load memtrack module
2019-11-07 11:18:40.825 6778-6778/org.flyve.mdm.agent.mqtt E/AndroidRuntime: FATAL EXCEPTION: main
    Process: org.flyve.mdm.agent.mqtt, PID: 6778
    android.os.FileUriExposedException: file:///storage/emulated/0/Download/Inventory.xml exposed beyond app through ClipData.Item.getUri()
        at android.os.StrictMode.onFileUriExposed(StrictMode.java:1960)
        at android.net.Uri.checkFileUriExposed(Uri.java:2348)
        at android.content.ClipData.prepareToLeaveProcess(ClipData.java:942)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9854)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9860)
        at android.content.Intent.prepareToLeaveProcess(Intent.java:9839)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1610)
        at android.app.Activity.startActivityForResult(Activity.java:4487)
        at android.app.Activity.startActivityForResult(Activity.java:4445)
        at android.app.Activity.startActivity(Activity.java:4806)
        at android.app.Activity.startActivity(Activity.java:4774)
        at org.flyve.inventory.InventoryTask.shareInventory(InventoryTask.java:320)
        at org.flyve.mdm.agent.core.permission.PermissionModel$2.onClick(PermissionModel.java:70)
        at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:167)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2019-11-07 11:18:41.813 2449-8113/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 2585, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
2019-11-07 11:18:41.822 2449-8113/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
2019-11-07 11:18:41.822 2449-8113/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
2019-11-07 11:18:41.823 2449-8113/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
2019-11-07 11:18:42.057 2151-5947/com.google.android.gms.persistent E/ctxmgr: [ProducerStatusImpl]updateStateForNewContextData: inactive, contextName=7 [CONTEXT service_id=47 ]
2019-11-07 11:18:42.095 2151-2151/com.google.android.gms.persistent E/BeaconBle: Missing BluetoothAdapter
2019-11-07 11:18:42.119 2151-2151/com.google.android.gms.persistent E/BeaconBle: Scan couldn't start for Places
2019-11-07 11:18:46.872 2449-8114/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 2593, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
2019-11-07 11:18:46.873 2449-8114/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
2019-11-07 11:18:46.873 2449-8114/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
2019-11-07 11:18:46.873 2449-8114/com.google.android.googlequicksearchbox:search E/ActivityThread: Failed to find provider info for com.google.android.apps.gsa.testing.ui.audio.recorded
2019-11-07 11:18:46.896 2449-2472/com.google.android.googlequicksearchbox:search E/ReloadingLock: Finalizing LOCKED Token[shortcuts 2019-11-07 11:18:41.852]
2019-11-07 11:18:51.912 2449-8114/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 2601, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
2019-11-07 11:18:51.913 2449-8114/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
2019-11-07 11:18:51.913 2449-8114/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
2019-11-07 11:18:56.126 1680-1699/system_process E/memtrack: Couldn't load memtrack module
2019-11-07 11:18:56.945 2449-8114/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 2609, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
2019-11-07 11:18:56.945 2449-8114/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
2019-11-07 11:18:56.946 2449-8114/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
2019-11-07 11:19:01.972 2449-8114/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 2617, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
2019-11-07 11:19:01.972 2449-8114/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
2019-11-07 11:19:01.972 2449-8114/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
2019-11-07 11:19:07.023 2449-8114/com.google.android.googlequicksearchbox:search E/AudioRecord: Could not get audio input for session 2625, record source 1999, sample rate 16000, format 0x1, channel mask 0x10, flags 0
2019-11-07 11:19:07.024 2449-8114/com.google.android.googlequicksearchbox:search E/AudioRecord-JNI: Error creating AudioRecord instance: initialization check failed with status -22.
2019-11-07 11:19:07.024 2449-8114/com.google.android.googlequicksearchbox:search E/android.media.AudioRecord: Error code -20 when initializing native AudioRecord object.
```

**Comment by rrqq** [comment]
Moved to - https://github.com/flyve-mdm/android-inventory-library/issues/239
